### ISSUE TITLE
How to add this to a text box/ text area

### ISSUE THREAD

**Issue by ankesh27** [TheSmiths-Widgets/ts.floatlabelfield#1]
Please leave an example on how to add this to a textbox / textarea as shown in the demo animation.

**Comment by PierreGUI** [comment]
Hi Ankesh,
It's in my TODO list to add support for JVFloatLabeledTextView, I'll do my best to bring this feature ASAP ;)
Cheers

**Comment by ankesh27** [comment]
Cool! but then, what does the module do now ? ;)

**Comment by PierreGUI** [comment]
This module wraps the JVFloatLabeledTextField, means you can have this fancy labeled TextField in your titanium app.

**Comment by ankesh27** [comment]
how to add that label in s text field?

**Comment by wienke** [comment]
Thanks for providing feeback. Please also include the effort you took into trying to understand how make this module works for you and how to make this repository better.

**Comment by PierreGUI** [comment]
Done! Please refer to readme or example app.js to use TextView ;)
#1
